services:
  zookeeper:
    container_name: zookeeper
    ports:
      - 2181:2181
    image: zookeeper 
  cp-kafka:
    container_name: kafka
    ports:
      - 9092:9092
    links:
      - zookeeper:zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    image: confluentinc/cp-kafka
  db:
    container_name: db
    ports:
      - 5432:5432
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  go-tic-tac-toe:
    build:
      context: ./app
      target: dev
    develop:
      watch:
        - action: sync
          path: ./app/frontend/
          target: /app/frontend/
        - action: sync
          path: ./app/backend/
          target: /app/backend/
    container_name: go-tic-tac-toe-dev
    ports:
      - 3000:3000
    image: go-tic-tac-toe-dev
    depends_on:
      - zookeeper
      - cp-kafka
      - db
  mqtodb:
    build:
      context: ./mqtodb
      target: dev
    develop:
      watch:
        - action: sync
          path: ./mqtodb/
          target: /app/
    container_name: mqtodb-dev
    image: mqtodb-dev
    depends_on:
      - zookeeper
      - cp-kafka
      - db

volumes:
  postgres_data: