services:
  zookeeper:
    container_name: zookeeper
    ports:
      - 2181:2181
    image: zookeeper 
  cp-kafka:
    container_name: kafka
    ports:
      - 9092:9092
    links:
      - zookeeper:zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    image: confluentinc/cp-kafka
  go-tic-tac-toe:
    build:
      context: .
      target: prod
    container_name: go-tic-tac-toe
    ports:
      - 3000:3000
    image: go-tic-tac-toe
    depends_on:
      - zookeeper
      - cp-kafka
  db:
    build:
      context: ./db
      target: prod
    container_name: db
    ports:
      - 5432:5432
    image: db
    depends_on:
      - zookeeper
      - cp-kafka